language: r
sudo: true

before_script:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev libproj-dev libgeos++-dev

notifications:
    email:
      on_success: change
      on_failure: change
