language: r
r:
  - devel
sudo: true
dist: xenial
cache: packages

before_install:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev libproj-dev libgeos++-dev r-cran-rjava

notifications:
    email:
      on_success: change
      on_failure: change
